language: python
python:
- '3.6'
branches:
  only: master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam build
- sam package --output-template-file packaged.yaml --s3-bucket excelkiller1
deploy:
  provider: script
  script: sam deploy --template-file packaged.yaml --region us-east-1 --capabilities
    CAPABILITY_IAM --stack-name aws-excel-killer
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: PJvORS/WJ5ckAyRRRl8yzNZ7IZxhmKVfFpgerMZ1Y3XT5lZwNxGlHciDdMWAUKes7AJICPNReF45U4q/KXDpb+xt8J1asUmT0e9u9tZAdPm2YTmxA0QDw7gARlouveHfGdre4ZyOZaXAdC1T8nVtgdDfJdOt18xwMP34RUM6MeHUC7qX28HjY6cWQ+MEr8fmG2gbCrPDdecxJfmHScjNV4GwkEuK+A1w43wYLS9FZuzSZTS6Sa2cbGkOIocQqqPGvDtBYnyCQYAEMF5P7yZmcXrY/FmyGkxj1jldvYRQpvn/yWPwb/1D+EZlx+DBm6u/15+oWgPjzeZIylobe4paXIzAgfrZgUqDfrvWbNgnrdjEQIyf+dtbEBctYD60IasjexM5I46XhbXh1ht3jaGrFV0ecMYLRSY404r54HeYiLU4rf8mFUY0MhHRNdEssSNykqBwOM/CMqIZvTs97JtWH7+ICmk27q+MvZQeeJOQXBHTlSI2YFDLa41qNjiazxCWU+JZHXzjsfYykdNhX3tdgD4QjRrXDguFAqhD5QtGHEkOyHXn135MxaDe9rs0IxSeBCkvixLCYPZ85U3Iop5gnSw2ydZWt+Rc94NZ2ZQWpJzCVxRCKdE+AaXEa4jLxXOtFr4Afcm6I+r2YvWM6cgmTiooTwVNEdEgAXeoWCI9WXA=
  - secure: Hj0rLkR7eETDzb4MRfOkAeDNbXJRkivEBG4vkTnnpT5728WxG+MpQN92dvigQMjNNwV+6SKRVI4cgGf/wyShLjMWAjLpbVt/BC/0GhOWbgIonaqo+J8xntaLzmwnSeVnggYE3p11OhgaF35QPwi/ZvrIVENja1qOPzVeEpIzp37AB3g0tsThbnyRa5+4ASU5nugDXRPw3+6zwl2R3pFSQmKLWFMmjEx9UcGSPz8gaDBeQB2MaL7bgefCS2Jy7YrcyyzTwyg7nvcQLZyaKp59ZAPl9zQjXGjJFn5KAQTnTgYiNW4Xn0ijwQocKuZ4JYJK46W/mjolRIfmdsZWTJ8SVy7aiOiCQ1T9xsOdg7LsqRg2s2ojlQaxe04KtyC2IDax72Rf395mwcFKy+1ZwwxEFoMQHJtrw/nDJ8+JJi9sAbZMC0tfJIcCHuIjMWzUKRkS7wESWYfJKQc+t66uctShV2WqtJ7GIMs87QpETCdy4eNa8NXHDFY7XzpgyScVYoxLy/CVo3MkH3RzQ4HZerj5SlTETzJNLOQZykMFDpLknz4vnkv/QMAJ9GxjpNEoFdxRVaqvmF0vTulpkQ0F/i15+gmrrZG3QLqT7OwoEL7NKtvVWWJPyTHAJU8pnjXH4ItQ40rgDYYHgmKR/cXe9TwDPZ8PynVSR64/uKXIQwSumoM=
  - secure: OogcBTBTOmgW0fMTVUWt1JapIb9CqBwSjFciHDHhzW2h/ZMPWwd434nN3DgDyR8chJ4SGq8Dmmm5u3XwCs2P9RuK3z8X0EE8ceSOHSoFzbdUo0LNT9TiG9v98dBEewapMq6I3dmBrYG4IQclLcIb5Tr6cJIxo+VkXkef+9O1BzTtVORhh+hriAOod4zFbpcH4C37j+kYN7Y3//OAlMxlq9J1+hlSzdcRy+mMbpYKWoO2/HaQoOxQNFHMreijEg6JN5GTOueYT/nk4tB//PLWJoQzgJL60ccVr/cwhEns/GjGKr5CdcuaUaak2ST9z36APNXPe6wrJWgIbxCRJ4GKBiCi+4rnrLEfv59FxVMclA7lQRFlWV380h7qvGDeQWWioJGmH4U/pEGExxxuKSehpegDA1iWMiYQoU4/63luRae20rLKlgVSvHq5057USm3pkNn39ANjjqdQM/THE6SCcAQtUU8v/lMIG4cB6f13You/ETYwR/8jKEiFuuQ1jXWm1np0Zat9AjzAFo/SjPB578/16R3YgeeE3zM4dewXspJGAwUu5O7tr5bQSLo9Pbo8304AVuZbNcN2gXdMbdcUIpgmn2WGou7fWZyo1Hy/OjE2gjyy/QDItOSGsF8jqLVnPmDCkpudNvNMhrdWUg2F1RnPXkAsX/X2m7BVNPfot2s=
