language: python
python:
- '3.6'
branches:
  only: master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam build
- sam package --output-template-file packaged.yaml --s3-bucket excelkiller1
deploy:
  provider: script
  script: sam deploy --template-file packaged.yaml --region us-east-1 --capabilities
    CAPABILITY_IAM --stack-name aws-excel-killer
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: QpSXcevdyWq8DIV/l8goidMoytA44g5u/bl1NHb4hdqptH9vVtrjHhRKi+3q0LyL4WXL1JPdCE7yVbXXSXt1FjJIU27/XRN0Bc09eP+Ma02T78vzm16F+BCheI2kw7/zc6gGwRQdaEGsTgx9husrEg4ror+t1mmGLU4TLY5ePKUC0e8otOY9Uc4+PUZmiOQLBqa5WAuVkYowiCyTk0xGy9+IwAGOMoeVZq/NqzbTk8vvifDi0emnls0Osgu93fqes1CX2pKEFykPueoemm73IfNmxIX1N5wGBJ9Mg8cLqK42QnOxXt6jDbclHUrx/OcYrQZnhg8EqGeKMRj9bXXtUkSG/QtkQVi23Y9ncYGBryUEWF6LFBE3UJqr33YQqueakz2DoKikWZcndsKALD0e7NaPWxcE5At3T6FkUNqxuGJvV4+ZhCAvCUcFYhpKwb09Ye5ILh5fVqtYf+k4MMqizKKpYJyFoAcY6Pq/3jok1l3KcA2pm65QXj+h84QoV98HRIq08rpu8MBPCsGrLUcvA4OmpbdUedWqidm433GmqhnWEfaNovQP4ckwVU6DguqGgYA50mdLEu2qABxlyZ4we6Ap7vV0aaAjkJF3/QCKlOfT4avmIRepBw3mWOevUytrTQJ15mAdwponyHeTEFGeA3HQKUVJgArTAgiqn39YYns=
  - secure: iQz7Wcze0mDA3ZxYM0j5kPwCuX5ZdSbWbkXdtC5Q0Qo46HVMK48J13zqHRx+iRDX5+05AcScnQjLomzdPBIWDBEku62WaTkCfgMu9LMRS2nQec/EmxeELk/LrZRGXThfRvRMt9PPHERGcsnH2OCjk6BIdsEIY1UfKCD9aBfuv0a6Q9UkeLGocjyfL+J8TUr4ldzhC8XQHl8GrmdMk1ZMglHbYYvMO96eU8fEdlqrkZokpzcvt2KVCAq3TKwAnaO4SiK9P0kt5s2fLZTyE/PodA18fTDPYyrGFB/ZBCT6UxWaPW8IMyTDWe8hD5zQe0/yjLrCiVKzCoyIxO+QGcvmUxl5KDKR5PtAYlqHagE/SZX/605zrJa8uLTer9UwtW7r7pkScR8B1Fcd8bQEtZshSu6/rTeStb+tcK/BQ5Buxjfi1nvFF0LlAlxKS8pZoWr+Wq1lL3ymEnDhM7VR5qgbYKB5+37xcjriIiWcb2Rxk4gmvLN1hnpQI3COudJexxdIlYJ8Se41zxSTJgNrqp39m2oIlsMLf6n4OPm9Bx0uqYp43l3TK63YU8Q6QMWpomBvKrQEcFTVWvrPwSd8IUnm0A8RW0brOABqh3Kc7jkKQQ6Hi1qivsRoyVexXUgPLKu60qrh5zqbbs3G29LZr8WoyAsAlMBrz3KsInkvrkXdg7E=
  - secure: GQoY8jJywCz6jJtPuf/rVdolH7Vqi9WZbDH1iN5aneaMnZcZknJEqrC4gdAEegpdPTXfBR5pd2/Ljgz7Tx9T3a2vk7EpNGZp0n037EMy5SYPqNe+dXqCZZtzbABnl/vx6ORZRx9J/mkwdv9510FIj7w61JuvtiQp9YJk5cEapTBA4HlV+/YezR8U8H8lqFIwUrB+HgbKSktoZPp7jM+AqvdacxjVZKwBU4s/0xKJcaTLvq7kFRDDb4bwbc3HJaf6a/m/LjLteRshEPa0RR4iSmRzfYPoGGPhMSO9KqJJocX9z7S4z9Zsu5dqSU6mVuSnPgsDIfXYzQS6wU8tDUA2UJFD2EHfARxH6Y+wEbHrQlL5BZ/06vw6vJDoU/4xEPffvQ2UBxXARD8uXwJhYBgQROLil/N64oFwpueRc0EPw8tPpaHW0Lc2rty+zg0luyNhJh+7nKDiNcpcT1vP5M7FXdt77okxMxRcTIGDrgZitMFhSmfDpPqzCjuN8w5ZorU7XU5YE4nBZwgmrg+lN+Hxqu4FAmgDqN6MQ2dQ8X94f+GNjw4P1qv1+kimIbbWtPc+L739E5Wpm9FhaTePEaKXUiHGEM4B/+iolVyQEu5Ws0XV6imyLp5ipK2KC41MmeDeguBneGEmZpEbkaYB7YuqWfzTRsdE95Iy/jbvZBYrnbc=
  - secure: KhDwpONUHaRv5chEE+31civi5rKBCLlN3xREEBKPpP+9xVw/49HQYObjxxUVHkAz/+M9VymhhSzW9Vchzx/DOBsJiQdMx57RzFC9FpcyW27yijYqcpY/NMoUbVJJpCXxbBa1NGPD0DrgCgUkVc6ssOFraeG6PAdI89Y6RkZez7Slpw34XdUB/ORfkwJST3hjGSoKJGjEdpgwe4lvInxT9OJEVXT8T19byZavV8ez6yU1BZcUgHkx5Kg6/Q5dNVDcQPOI8DcR70ARgqMYt/HUzFevOr1yz5v3SHGCiJWL33We4fuvkIBZNcpz8GhsaPFwQ8tbIGxOZXxqTgR/Y0ljHVy+/Mi2kwO5G0s5Cefxd0Ih1T179BUWToiog9rYw9R7vitby9wKer/ywe988UwHEQ2ColTk2HkhdwCPeAOI/fCMHyJ87NPqkg4bjnwXDFJcnxkhsY7Sz9JYkeocXv/2O90uzd2OsPEPkjDuvEu9Jrg835DFjC0ct4ou0oOqHNC1f2K5BsLATmGPHrBREtu2mqKA9DCJSi5h1LWhbOzWu41xCuJcFNTLPtwlMuaVT3W4mR0hsLtDw8qhPVKrLam3kRHH41tksyQkWXboSYjqQI0InaZ6w9INewRpKMlWFHWzPko/uond/De11c46aA0YRBkz/jrQNZOxtHojuNXz90I=
