language: python
python:
- '3.6'
branches:
  only: master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam build
- sam package --output-template-file packaged.yaml --s3-bucket excelkiller1
deploy:
  provider: script
  script: sam deploy --template-file packaged.yaml --region us-east-1 --capabilities
    CAPABILITY_IAM --stack-name aws-excel-killer
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: NgR/+z+DEjojV0WQAKRic1kZfCSh0nDnrdvELxS92P/gF29qVnhDtwu4+JxYVK/Q2BduaYA09XC/POxqgJJTzXdKQ9oBrPc84W4OU7i2ctQj6ejDea2rYoBIMEcaX+l5WVrn/nWNp66H8MrrVvfW7TLDmezhahhzDyuyUYQI8UJIB80FGB+AD66OmdEjb+9Q8M6Y+LnJ1fWgkOkxUX9AfkiZAbf4lJ/ltboZS7ai280pVCHVnbo07gMocT8Z447a6vGF6mhLq4BgjJd7MoOLxAKLuU1ranjegDoSTRjL3fmlopaAV/BEQDLAawVSXsO8BkB7EbuJVxBhxoUYJlnzg3Weg2NVnIrr7Rebb/doGI3z/hWUJFawSfc+h/YGFh8jafyCLid/ZABtvOPOyZoFnHLyD2/nMa2BnvWpN2Kle9BFPegpsBk79WWK89ZTgc/gwFyU7EA18WQ9qqA946sYte7VkZcGdYTdvtqj1eDtxMsPgKH3QibKiKkUQTffz8WbGHWQjf9mbIS6Xem6dHmZouqh0O6zYd0fkzSedcIeGzUERpuC56EInpyRiHtCFluklhx3+VabSsJ1l0uBoC6oEhIyWlaFizbSmSiNVdTcQp29iA9NSON9S3yvkzw1I3C03NVQKUhTWLahk3Bt4mKPkKmzrutsxVxlNUo8S0XJmm8=
  - secure: TgbPHTZHOD/hcvVAIWXSrv+KhvrPFlXn85/n9GlFcpZz1ms2XsQBCMlpxitqQBmvCbMY+BQ303xFwgwimknjGkc+JWkGtC+GzTFKsYpFvRhgas4KEuE91eLUkPnCzfOoo9OtYkJSiLqQav25R8PHMj3gHlqMH1njIB0sET4t8Gb4WUbfwRmU3m/MrlPN25gzriL3QmLjEA+vJ6zShR2WJxUBPaJud/ByvOn7kWJFUIFbwEdBMWo40xZtbhAcUSUvAjWNxItii72Uy66oI+SNnywepieMQWt8h16YKAaWu5DdaRAdzKE9ch3PJ+ZpWGAm1gjNppcgoJQUhd2SxJWQE+JqWlhNxiEwAE7nLAy7tzVcWF9XU96q8SKcJvfODvg55rN5gKqy7swbrx1zsA5+GhzhhUlF7JVzLOgF/ZJGIAPXrB369kdDYiI1NhmuRK50b232HN6xNFbQjOtvSLNj6wVRtU9llCzsKhlBTW3ZJIZnBg/Gn3l3P7M5ug+I1RfBVgHlzydjRpr36bMqHkSO2Zlvu1EWNInaxFHHq94zAkrWY07/uAIq+P3mO//yNW6YR6WqGQ5BCZqVJq+gHjid7mFauLp3GZNYlYBJ6zQTYZtXCsO392nfqxDUz3ozcnRGum5XM6Sqy2nRCnCD5BZFSzeUboGUOo8g7Kpq66cqM/w=
  - secure: geG2xfR8pd+qOsE78eJlWb+ZbavNHgxdI0GRFNOS4ze3oBROJ9mUrifyBjZFAbeyaUjJQfpbTG3AVkaZ0djAuS7+v7FYQISz+V6TZ1QcjagmP9L4TrgMyKYNjV5PzTjSQfbqKgUFccpV0Y3XWvrKvD+41KzUKz+L+lfHt7u+iO6YXAt/MIXZ/rA0W/GvQgvbTMe2xv9mgibBXpUdfribgTR6Sn9NJrQf7wGtoFaggw3n3L6Knfb/D7Vb3hKgpCGN2qdUVs2Q7PHrD/wU730yhHZ+hFfbUMHk2ZauTlyLF169BSlm2aQPCZ/PUeS3Dwe0uT/U9W4lsJgqpvBDt0WtQMu6UpNviCTdfmdiS+rzsHi8Bf37vBE0Ee1cG9LknGRMH8d9pNzE0vYizti876L9IDfLl8FKxRxccbJVxw8aDgnWFWY6f32A9twZJHblt2F5D0W75l3FNpDCSu99wtRkW5v5vo5jGfdsht/M7I95nYWI4CcEdpgRq+UnDu7qAgDkVc02cgVz20idNAe3/aROTddTztd67vXOhuuNydDqbiIP3bQuwF7a2NjRggaf7Dx3BUAy+6UKqEpj0FF/7em4pG8KWD5dJnrU7vTQdqqwUrn0Z7pC3wLSmPJDGrawuyAUYxpkzA50Skfb+0/FGuALt27P3q9FKNIrFJAKOkJT4I0=
