language: python
python:
- '3.6'
branches:
  only: master
install:
- pip install awscli
- pip install aws-sam-cli
script:
- sam build
- sam package --output-template-file packaged.yaml --s3-bucket excelkiller1
deploy:
  provider: script
  script: sam deploy --template-file packaged.yaml --region us-east-1 --capabilities
    CAPABILITY_IAM --stack-name aws-excel-killer
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
    secure: 2aHH7bBIF6Fb7TgjI6lx9NrFpKZCFMUYP1FmXKBd2bGD/zs4DwsjmsNEL3DTJhNtKvzMWBPxZziwTzMT6u9asYWJadPmKeWR8m3FD1dWcu9Juz8A+s1vNezVomVJmaqRdTs+Vf97j5KbvpuuYyBu4HznUHyztYjNoPOCl6QkNrp9agdoaTQqhQbmgArcf0+cef61803hn2HY8Ei3FUe503Ss+97P2AH4kkgOij9+iiNvecRQErJFnNLVpp5YsEoeyLvJHV7WLwBfMbvavlR36s3jRoFH2e9iGp6K5xdYBPkJGSd2wKcXz2HE6b5tPjmr4foTdls7bAwEFpwubQaHXuQHt9rezNGrr7e69sU4rfh0kC+JRzLpjegNQcfRRCwhz0qLPJfOameXvkbLQQqYCL6l8hvSK7RT8y67ItyLu4WppHySyEQBkrc/u6JaC4X5xMxq6FsdBwYvrnAAtaljTm9BA/aMWb34UV9Yu1WFMitLvctybHtZ8NjR97JRxjCZ6aRjU6sD764vy88Wr9a7WBQgcDlodVFOfY5eYIKPEgoaImsQBZm0aHiypaeUwzWVtEne1jJ0HCsDEyF0ZZGONSGc4osDWzqmtrR4tdwQH7+UBkZcXJDrHmPAO81wAD/w/zO1y7Ooj4uPFmn7eY6+ZDS7NuPZCJDZSFduv8332Vc=
