AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Excel Killer

  Template File

  '
Globals:
  Function:
    Timeout: 30
Resources:
  basicsActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/d6b0a17994e5e388b99af41a46d6fb85
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        basicsPandas:
          Type: Api
          Properties:
            Path: basics/
            Method: ANY
  understandingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/ba26c6c89ea10ef3ccbe556274a5de21
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        understandingPandas:
          Type: Api
          Properties:
            Path: understanding/
            Method: ANY
  cleaningActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/b44bbe2f03233cfd60e48e94c5deee40
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        cleaningPandas:
          Type: Api
          Properties:
            Path: cleaning/
            Method: ANY
  visualizingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/e0c0585dec1ca8e0a6a5ec2df4e57c14
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        visualizingPandas:
          Type: Api
          Properties:
            Path: visualize/
            Method: ANY
  landingPage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/f8a000bd34ff57da7d96c87578012739
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        landingPageExcelKiller:
          Type: Api
          Properties:
            Path: /
            Method: GET
