AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Excel Killer

  Template File

  '
Globals:
  Function:
    Timeout: 30
Resources:
  basicsActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/4ee0533b6ea7aebf4823ad8eb65dc906
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        basicsPandas:
          Type: Api
          Properties:
            Path: basics/
            Method: ANY
  understandingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/040c06d5eac0e60f61a9ceab13c9f475
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        understandingPandas:
          Type: Api
          Properties:
            Path: understanding/
            Method: ANY
  cleaningActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/e605151e9e5a7a4074867199e4865c20
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        cleaningPandas:
          Type: Api
          Properties:
            Path: cleaning/
            Method: ANY
  visualizingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/3a00b5c1f051595399e22f99b523923b
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        visualizingPandas:
          Type: Api
          Properties:
            Path: visualize/
            Method: ANY
  landingPage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/429daeabbf4ea1aeca47803cc74c87fe
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        landingPageExcelKiller:
          Type: Api
          Properties:
            Path: /
            Method: ANY
