AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Excel Killer

  Template File

  '
Globals:
  Function:
    Timeout: 30
Resources:
  basicsActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/ec421f48a79113446922c148f75f5946
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        basicsPandas:
          Type: Api
          Properties:
            Path: basics/
            Method: ANY
  understandingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/561ffc68b32cef05e3af2dbd85ef1e97
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        understandingPandas:
          Type: Api
          Properties:
            Path: understanding/
            Method: ANY
  cleaningActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/43a9df17d076b69c16a81acad74275eb
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        cleaningPandas:
          Type: Api
          Properties:
            Path: cleaning/
            Method: ANY
  visualizingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/63f0c3238174ab028e112d50bfd6330a
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        visualizingPandas:
          Type: Api
          Properties:
            Path: visualize/
            Method: ANY
  landingPage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/3c8d0ec6c3155321aeaa5c6924daeff3
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        landingPageExcelKiller:
          Type: Api
          Properties:
            Path: /
            Method: ANY
