AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Excel Killer

  Template File

  '
Globals:
  Function:
    Timeout: 30
Resources:
  basicsActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/d325101bf7d7730313b0278934833990
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        basicsPandas:
          Type: Api
          Properties:
            Path: basics/
            Method: ANY
  understandingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/759b19b938563393dfad2ab979e6cb76
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        understandingPandas:
          Type: Api
          Properties:
            Path: understanding/
            Method: ANY
  cleaningActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/b3947a509428569ff0a647eaa764d3d7
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        cleaningPandas:
          Type: Api
          Properties:
            Path: cleaning/
            Method: ANY
  visualizingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/5994f7511728cb2bdb54ea30b068cd6b
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        visualizingPandas:
          Type: Api
          Properties:
            Path: visualize/
            Method: ANY
  landingPage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/0365f7382383ed60653bea02204727a2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        landingPageExcelKiller:
          Type: Api
          Properties:
            Path: /
            Method: GET
