AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Excel Killer

  Template File

  '
Globals:
  Function:
    Timeout: 30
Resources:
  basicsActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/b0cb9e6bcd1f1f5337a1d1ee993b80a9
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        basicsPandas:
          Type: Api
          Properties:
            Path: basics/
            Method: ANY
  understandingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/ca2d2210412abc4131da9db24108e682
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        understandingPandas:
          Type: Api
          Properties:
            Path: understanding/
            Method: ANY
  cleaningActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/6d24d29399c1ba4d00aab163972cbb94
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        cleaningPandas:
          Type: Api
          Properties:
            Path: cleaning/
            Method: ANY
  visualizingActivity:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/1acfcca57b9e8ebd52dab35970cd48c7
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        visualizingPandas:
          Type: Api
          Properties:
            Path: visualize/
            Method: ANY
  landingPage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://excelkiller1/b8d3d73e7970054652d60753e372364b
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        landingPageExcelKiller:
          Type: Api
          Properties:
            Path: /
            Method: ANY
