AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Excel Killer

  Template File

Globals:
  Function:
    Timeout: 30

Resources:
  basicsActivity:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      # set codeUri to nothing if lambda_function.py is in root directory
      # if for instance, lambda_function.py in function folder, set codeUri to function/
      CodeUri: src/basics_act
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        basicsPandas:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: basics/
            Method: ANY
  cleaningActivity:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      # set codeUri to nothing if lambda_function.py is in root directory
      # if for instance, lambda_function.py in function folder, set codeUri to function/
      CodeUri: src/cleaning_act
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        cleaningPandas:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: cleaning/
            Method: ANY
  visualizingActivity:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      # set codeUri to nothing if lambda_function.py is in root directory
      # if for instance, lambda_function.py in function folder, set codeUri to function/
      CodeUri: src/cleaning_act
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        visualizingPandas:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: visualize/
            Method: ANY
  landingPage:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/app
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 1024
      Events:
        landingPageExcelKiller:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /
            Method: GET